In [1]:
import torch

In [2]:
x = torch.tensor(4.0)
y = torch.tensor(2.0)

In [3]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(2.0, requires_grad=True)

In [4]:
w

tensor(1., requires_grad=True)

In [5]:
b

tensor(2., requires_grad=True)

In [7]:
z = w*x +b

In [9]:
z

tensor(6., grad_fn=<AddBackward0>)

In [11]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9975, grad_fn=<SigmoidBackward0>)

In [13]:
y_pred.backward()

In [14]:
w.grad

tensor(0.0099)

In [15]:
b.grad

tensor(0.0025)

In [26]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

In [27]:
x

tensor([1., 2., 3.], requires_grad=True)

In [30]:
y = (x**4).mean()
y

tensor(32.6667, grad_fn=<MeanBackward0>)

In [31]:
y.backward()

In [32]:
x.grad

tensor([ 1.3333, 10.6667, 36.0000])

# Clearing Gradients

In [52]:
x = torch.tensor([[[2,55,4],[4,5,6],[7,8,9]]], dtype=torch.float64, requires_grad=True)

In [54]:
x

tensor([[[ 2., 55.,  4.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]]], dtype=torch.float64, requires_grad=True)

In [56]:
y = (x**2).median()

In [57]:

y

tensor(36., dtype=torch.float64, grad_fn=<MedianBackward0>)

In [58]:
y.backward()

In [59]:
x.grad

tensor([[[ 0.,  0.,  0.],
         [ 0.,  0., 12.],
         [ 0.,  0.,  0.]]], dtype=torch.float64)

In [60]:
x.grad.zero_()

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [61]:
# disable gradient tracking
x = torch.tensor(69.8, requires_grad=True)

In [62]:
x

tensor(69.8000, requires_grad=True)

In [63]:
y = x**2
y

tensor(4872.0405, grad_fn=<PowBackward0>)

In [64]:
y.backward()

In [65]:
x.grad

tensor(139.6000)

# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [67]:
x.requires_grad_(False)

tensor(69.8000)

In [68]:
x

tensor(69.8000)

In [69]:
y = x**3

In [70]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [71]:
x = torch.tensor(4.3, requires_grad=True)

In [72]:
x

tensor(4.3000, requires_grad=True)

In [73]:
z = x.detach()

In [75]:
z

tensor(4.3000)

In [76]:
y = x**2

In [77]:
y

tensor(18.4900, grad_fn=<PowBackward0>)

In [79]:
y1 = z**2
y1

tensor(18.4900)

In [80]:
y.backward()

In [81]:
x

tensor(4.3000, requires_grad=True)

In [82]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [83]:
# Enable gradient tracking by default
x = torch.randn(5, 5, requires_grad=True)
y = torch.randn(5, 5, requires_grad=True)

print(f"x.requires_grad: {x.requires_grad}") # Output: x.requires_grad: True

# Operations inside this block will not track gradients
with torch.no_grad():
    z = x + y
    w = z * z
    print(f"z.requires_grad: {z.requires_grad}") # Output: z.requires_grad: False
    print(f"w.requires_grad: {w.requires_grad}")

x.requires_grad: True
z.requires_grad: False
w.requires_grad: False
