In [3]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)   # z = wx+b
    out = self.sigmoid(out)   # y_pred = sigmoid(z)

    return out


In [4]:
features = torch.rand(10,5)

model = Model(features.shape[1])

# forward propagation - y_pred
model(features)

tensor([[0.5487],
        [0.5354],
        [0.4903],
        [0.5256],
        [0.5270],
        [0.4506],
        [0.4683],
        [0.5256],
        [0.5056],
        [0.5738]], grad_fn=<SigmoidBackward0>)

In [5]:
model.linear.weight  # show model weights

Parameter containing:
tensor([[-0.3165, -0.0592,  0.3435,  0.0673,  0.1091]], requires_grad=True)

In [7]:
model.linear.bias  # show model bias

Parameter containing:
tensor([0.0076], requires_grad=True)

In [8]:
pip install torchinfo

In [9]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00