In [1]:
import torch

In [2]:
torch.__version__

'2.9.0+cpu'

In [4]:
torch.cuda.is_available()

True

In [6]:
torch.cuda.get_device_name()

'Tesla T4'

# Creating a Tensor

In [5]:
# using Empty
a = torch.empty(2,3)

In [6]:
a

tensor([[-1.3915e-09,  4.4840e-41, -1.3915e-09],
        [ 4.4840e-41,  0.0000e+00,  0.0000e+00]])

In [7]:
type(a)

torch.Tensor

In [8]:
# Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# Using Ones
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.rand(3,3,4)

tensor([[[0.2804, 0.7557, 0.5017, 0.9557],
         [0.8830, 0.7063, 0.5859, 0.8867],
         [0.4535, 0.3692, 0.3950, 0.7770]],

        [[0.8493, 0.2299, 0.3126, 0.2981],
         [0.9331, 0.4449, 0.2174, 0.7353],
         [0.4856, 0.8160, 0.1839, 0.4639]],

        [[0.4825, 0.2344, 0.8171, 0.5750],
         [0.8617, 0.4255, 0.2597, 0.5628],
         [0.1853, 0.4604, 0.0409, 0.3944]]])

In [14]:

torch.rand(3,3)

tensor([[0.1178, 0.4648, 0.3986],
        [0.4689, 0.3025, 0.7039],
        [0.8416, 0.6520, 0.6011]])

In [16]:
# Using manual_seed() using same value we can generate same value using rand
torch.manual_seed(1000)
torch.rand(3,3)

tensor([[0.3189, 0.6136, 0.4418],
        [0.2580, 0.2724, 0.6261],
        [0.4410, 0.3653, 0.3535]])

In [18]:
torch.manual_seed(1000)
torch.rand(3,3)

tensor([[0.3189, 0.6136, 0.4418],
        [0.2580, 0.2724, 0.6261],
        [0.4410, 0.3653, 0.3535]])

# Creating Tensors using Tensors


In [23]:
a = torch.tensor([[1,2,3],[9,7,6]])

In [24]:
a

tensor([[1, 2, 3],
        [9, 7, 6]])

In [26]:
type(a)

torch.Tensor

In [28]:
# Other ways
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
torch.linspace(0,11,10)

tensor([ 0.0000,  1.2222,  2.4444,  3.6667,  4.8889,  6.1111,  7.3333,  8.5556,
         9.7778, 11.0000])

In [32]:
# Identity Matrix of 5x5
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [34]:
torch.full((4,4),110)

tensor([[110, 110, 110, 110],
        [110, 110, 110, 110],
        [110, 110, 110, 110],
        [110, 110, 110, 110]])

In [35]:
x = torch.tensor([[3,3,3],[4,4,4]])

In [36]:
x.shape

torch.Size([2, 3])

In [39]:
# generate same dimension array of x but using empty
torch.empty_like(x)

tensor([[3616445622929465956, 6066683143718448438, 3761695593172973616],
        [6498750583060641326, 7309453675965983778, 8315168162784306286]])

In [40]:
x

tensor([[3, 3, 3],
        [4, 4, 4]])

In [43]:
# generate same dimension array of x but using ones
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [44]:
# generate same dimension array of x but using zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [45]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.5971, 0.3572, 0.4807],
        [0.4217, 0.1254, 0.6818]])

# Tensors datatypes

In [46]:
x.dtype

torch.int64

In [49]:
z = torch.tensor([[3,3,3,34],[5,5,5,5]], dtype=torch.float64)

In [51]:
z.dtype

torch.float64

In [52]:
x.to(torch.float64)

tensor([[3., 3., 3.],
        [4., 4., 4.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

# 1.Scaler Operations

In [53]:
b = torch.rand(3,3)

In [54]:
b

tensor([[0.0571, 0.6818, 0.0473],
        [0.4856, 0.0260, 0.0131],
        [0.7607, 0.0722, 0.1026]])

In [58]:
b = b+2

In [59]:
b

tensor([[2.0571, 2.6818, 2.0473],
        [2.4856, 2.0260, 2.0131],
        [2.7607, 2.0722, 2.1026]])

In [60]:
b-2

tensor([[0.0571, 0.6818, 0.0473],
        [0.4856, 0.0260, 0.0131],
        [0.7607, 0.0722, 0.1026]])

In [61]:
b*2

tensor([[4.1143, 5.3637, 4.0946],
        [4.9713, 4.0521, 4.0262],
        [5.5214, 4.1444, 4.2051]])

In [62]:
b**2

tensor([[4.2318, 7.1923, 4.1914],
        [6.1783, 4.1048, 4.0525],
        [7.6215, 4.2940, 4.4207]])

In [63]:
b/2

tensor([[1.0286, 1.3409, 1.0236],
        [1.2428, 1.0130, 1.0065],
        [1.3803, 1.0361, 1.0513]])

In [64]:
b//2  # divide and round off

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [65]:
b%2

tensor([[0.0571, 0.6818, 0.0473],
        [0.4856, 0.0260, 0.0131],
        [0.7607, 0.0722, 0.1026]])

# Element wise Operation

In [66]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3915, 0.4430, 0.6577],
        [0.4261, 0.3461, 0.6818]])
tensor([[0.8130, 0.2286, 0.6463],
        [0.9791, 0.8770, 0.9927]])


In [68]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3915, 0.2144, 0.0113],
        [0.4261, 0.3461, 0.6818]])

In [69]:
c = torch.tensor([1, -2, 3, -4])

In [70]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [71]:
c

tensor([ 1, -2,  3, -4])

In [72]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [73]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [74]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [75]:
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [76]:
torch.round_(d)  # using Underscore after method makes (inplace=true)

tensor([2., 2., 4., 4.])

In [77]:
d

tensor([2., 2., 4., 4.])

In [78]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [80]:
# ceil
torch.ceil(d)

tensor([2., 2., 4., 4.])

In [81]:
# floor
torch.floor(d)

tensor([2., 2., 4., 4.])

In [82]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2., 2., 3., 3.])

### 3. Reduction operation

In [83]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[0., 7., 5.],
        [8., 4., 8.]])

In [85]:
# sum
torch.sum(e)


tensor(32.)

In [86]:
# sum along columns
torch.sum(e, dim=0)


tensor([ 8., 11., 13.])

In [87]:

# sum along rows
torch.sum(e, dim=1)

tensor([12., 20.])

In [88]:
# mean
torch.mean(e)

tensor(5.3333)

In [89]:
# mean along col
torch.mean(e, dim=0)



tensor([4.0000, 5.5000, 6.5000])

In [90]:
# median
torch.median(e)

tensor(5.)

In [91]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [92]:
# product
torch.prod(e)

tensor(0.)

In [93]:
# standard deviation
torch.std(e)

tensor(3.0768)

In [94]:
# variance
torch.var(e)

tensor(9.4667)

In [96]:
# argmax - maximum among all
torch.argmax(e)

tensor(3)

In [98]:
torch.argmin(e) # argmin- minimum among all

tensor(0)

### 4. Matrix operations

In [99]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)


tensor([[3, 1, 8],
        [5, 8, 5]])
tensor([[4, 4],
        [4, 7],
        [8, 8]])


In [100]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 80,  83],
        [ 92, 116]])

In [101]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [102]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 5],
        [1, 8],
        [8, 5]])

In [103]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 8., 2.],
        [7., 8., 9.],
        [3., 7., 5.]])

In [104]:
# determinant
torch.det(h)

tensor(-37.0000)

In [105]:
# inverse
torch.inverse(h)

tensor([[ 0.6216,  0.7027, -1.5135],
        [ 0.2162,  0.0270, -0.1351],
        [-0.6757, -0.4595,  1.2973]])

### 5. Comparison operations

In [106]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[2, 3, 8],
        [3, 0, 3]])
tensor([[9, 6, 5],
        [7, 7, 3]])


In [107]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[ True,  True,  True],
        [ True,  True, False]])

### 6. Special functions

In [108]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 3., 4.],
        [1., 5., 4.]])

In [109]:
# log
torch.log(k)

tensor([[1.9459, 1.0986, 1.3863],
        [0.0000, 1.6094, 1.3863]])

In [110]:
# exp
torch.exp(k)

tensor([[1096.6332,   20.0855,   54.5981],
        [   2.7183,  148.4132,   54.5981]])

In [111]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 1.7321, 2.0000],
        [1.0000, 2.2361, 2.0000]])

In [112]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9526, 0.9820],
        [0.7311, 0.9933, 0.9820]])

In [113]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9975, 0.1192, 0.5000],
        [0.0025, 0.8808, 0.5000]])

In [114]:
# relu
torch.relu(k)

tensor([[7., 3., 4.],
        [1., 5., 4.]])

## Inplace Operations

In [115]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1503, 0.6447, 0.8081],
        [0.0081, 0.3580, 0.2408]])
tensor([[0.8467, 0.8249, 0.4714],
        [0.1823, 0.0104, 0.0601]])


In [116]:
m.mul_(n)

tensor([[0.1272, 0.5318, 0.3810],
        [0.0015, 0.0037, 0.0145]])

In [117]:
m.add_(n)

tensor([[0.9739, 1.3566, 0.8524],
        [0.1838, 0.0141, 0.0746]])

In [119]:
torch.relu(m)

tensor([[0.9739, 1.3566, 0.8524],
        [0.1838, 0.0141, 0.0746]])

In [123]:
torch.relu_(m)   # inplacce

tensor([[0.9739, 1.3566, 0.8524],
        [0.1838, 0.0141, 0.0746]])

In [122]:
m

tensor([[0.9739, 1.3566, 0.8524],
        [0.1838, 0.0141, 0.0746]])

# Copying a Tensor

In [137]:
a = torch.rand(4,4, dtype=torch.float64)
b = torch.rand(4,4,dtype=torch.float64)

In [138]:
a

tensor([[0.8925, 0.3810, 0.0188, 0.1977],
        [0.7289, 0.6161, 0.3652, 0.2443],
        [0.3942, 0.3569, 0.4932, 0.8687],
        [0.9106, 0.6420, 0.5738, 0.2259]], dtype=torch.float64)

In [139]:
b

tensor([[0.2591, 0.7122, 0.6880, 0.1973],
        [0.8045, 0.4773, 0.6825, 0.8627],
        [0.1912, 0.6758, 0.3296, 0.0096],
        [0.3724, 0.2433, 0.7612, 0.9017]], dtype=torch.float64)

In [140]:
b = a.clone()   # copying s tensor with another memory reference

In [143]:
b[0][1] = 10

In [144]:
b

tensor([[ 0.8925, 10.0000,  0.0188,  0.1977],
        [ 0.7289,  0.6161,  0.3652,  0.2443],
        [ 0.3942,  0.3569,  0.4932,  0.8687],
        [ 0.9106,  0.6420,  0.5738,  0.2259]], dtype=torch.float64)

In [145]:
a

tensor([[0.8925, 0.3810, 0.0188, 0.1977],
        [0.7289, 0.6161, 0.3652, 0.2443],
        [0.3942, 0.3569, 0.4932, 0.8687],
        [0.9106, 0.6420, 0.5738, 0.2259]], dtype=torch.float64)

In [146]:
id(a)

137436246250096

In [147]:
id(b)

137436246267280